services:
  samba:
    image: diegogslomp/samba-ad-dc
    container_name: samba
    hostname: samba
    privileged: true
    environment:
      # The Kerberos realm / full Active Directory DNS domain name
      - REALM=CORP.LOCALDOMAIN
      # The NetBIOS name / Windows legacy domain identifier
      - DOMAIN=CORP
      - ADMIN_PASS=Devsecops@mcl2026
      # DNS server Samba will query when it cannot resolve something itself
      - DNS_FORWARDER=8.8.8.8
      # This overrides the strict binding, forcing Samba to listen on 0.0.0.0 so other containers can reach it
      - BIND_NETWORK_INTERFACES=false
    networks:
      - samba_network
    volumes:
      - smb:/var/lib/samba

  keycloak:
    image: keycloak/keycloak:26.3
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8081:8080"
    networks:
      - samba_network
    volumes:
      # - keycloak_data:/opt/keycloak/data       # volume for version keycloak/keycloak:26.6 already full
      - keycloak_data_26.3:/opt/keycloak/data

  sonarqube:
    # password: Password@123
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - samba_network
    volumes:
      - sonarqube_data:/opt/sonarqube/data

  grafana:
    # password: Password@123
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP=true
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - samba_network

  terraform:
    image: hashicorp/terraform:1.15.6
    container_name: terraform
    working_dir: /workspace
    volumes:
      - ./keycloak-terraform:/workspace
    profiles:
      - "cli-tools"
    networks:
      - samba_network

networks:
  samba_network:
    driver: bridge
    
volumes:
  smb:
  keycloak_data_26.3:
  sonarqube_data:
  grafana_data: